version: '3.9'

services:
  server:
    build: .
    container_name: 'urlshortener_server'
    depends_on:
      - database
    networks:
      - urlshortener-network
    volumes:
      - .:/var/www/shortener

  proxy:
    image: nginx:1.9.15-alpine
    container_name: 'urlshortener_proxy'
    ports:
      - target: 80
        published: 8080
        protocol: tcp
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./public:/var/www/shortener
    networks:
      - urlshortener-network
    depends_on:
      - server
      - database

  database:
    image: postgres:14.2-alpine
    container_name: 'urlshortener_database'
    environment:
      - POSTGRES_DB=main_dev
      - POSTGRES_PASSWORD=app
      - POSTGRES_USER=app
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    networks:
      - urlshortener-network
    volumes:
      - urlshortener-database:/var/lib/postgresql/data

networks:
  urlshortener-network:
    driver: bridge

volumes:
  urlshortener-database:
    driver: local
